services:
  # Backend PHP
  backend-new:
    build: ./backend-php
    container_name: bpd-backend-php-new
    ports:
      - "5001:80"
    environment:
      - DB_HOST=mysql-new
      - DB_USER=root
      - DB_PASSWORD=root123
      - DB_NAME=bpd_database
      - DB_PORT=3306
    depends_on:
      - mysql-new
    volumes:
      - ./backend-php:/var/www/html
    restart: unless-stopped

  # MySQL Database
  mysql-new:
    image: mysql:8.0
    container_name: bpd-mysql-new
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: bpd_database
      MYSQL_USER: bpd_user
      MYSQL_PASSWORD: bpd123
      MYSQL_ROOT_HOST: '%'
    volumes:
      - mysql_data_new:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password --max_allowed_packet=67108864 --innodb_buffer_pool_size=256M

  # phpMyAdmin
  phpmyadmin-new:
    build:
      context: .
      dockerfile: Dockerfile.phpmyadmin
    container_name: bpd-phpmyadmin-new
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql-new
      PMA_USER: root
      PMA_PASSWORD: root123
      UPLOAD_LIMIT: 50M
      MEMORY_LIMIT: 512M
      MAX_EXECUTION_TIME: 600
    volumes:
      - ./phpmyadmin-config.ini:/usr/local/etc/php/conf.d/uploads.ini:ro
    depends_on:
      - mysql-new
    restart: unless-stopped

volumes:
  mysql_data_new:

networks:
  default:
    name: bpd-network-new